apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: university
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: uni-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uni-secret
              key: DB_PASSWORD
        readinessProbe:
          httpGet:
            path: /login
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: university
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
